/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface OfComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLOfComponentElement extends Components.OfComponent, HTMLStencilElement {}
  var HTMLOfComponentElement: {
    prototype: HTMLOfComponentElement;
    new (): HTMLOfComponentElement;
  };
  interface HTMLElementTagNameMap {
    'of-component': HTMLOfComponentElement;
  }
}

declare namespace LocalJSX {
  interface OfComponent extends JSXBase.HTMLAttributes<HTMLOfComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'of-component': OfComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


